name: "Update Test Results Badge"
description: "Posts test results to BadgeSmith API with HMAC authentication"
author: "LocalStack .NET Team"

inputs:
  platform:
    description: "Platform name (Linux, Windows, macOS)"
    required: true
  test_passed:
    description: "Number of passed tests"
    required: true
  test_failed:
    description: "Number of failed tests"
    required: true
  test_skipped:
    description: "Number of skipped tests"
    required: true
  test_url_html:
    description: "URL to test results page"
    required: false
    default: ""
  commit_sha:
    description: "Git commit SHA"
    required: true
  run_id:
    description: "GitHub Actions run ID"
    required: true
  repository:
    description: "Repository in owner/repo format"
    required: true
  server_url:
    description: "GitHub server URL"
    required: true
  api_domain:
    description: "BadgeSmith API domain"
    required: false
    default: "api.localstackfor.net"
  hmac_secret:
    description: "HMAC secret for BadgeSmith authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Update Badge (Unix/macOS)"
      if: runner.os != 'Windows'
      shell: bash
      env:
        INPUT_PLATFORM: ${{ inputs.platform }}
        INPUT_TEST_PASSED: ${{ inputs.test_passed }}
        INPUT_TEST_FAILED: ${{ inputs.test_failed }}
        INPUT_TEST_SKIPPED: ${{ inputs.test_skipped }}
        INPUT_TEST_URL_HTML: ${{ inputs.test_url_html }}
        INPUT_COMMIT_SHA: ${{ inputs.commit_sha }}
        INPUT_RUN_ID: ${{ inputs.run_id }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_SERVER_URL: ${{ inputs.server_url }}
        INPUT_API_DOMAIN: ${{ inputs.api_domain }}
        INPUT_HMAC_SECRET: ${{ inputs.hmac_secret }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: ${{ github.action_path }}/update-badge-unix.sh

    - name: "Update Badge (Windows)"
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        INPUT_PLATFORM: ${{ inputs.platform }}
        INPUT_TEST_PASSED: ${{ inputs.test_passed }}
        INPUT_TEST_FAILED: ${{ inputs.test_failed }}
        INPUT_TEST_SKIPPED: ${{ inputs.test_skipped }}
        INPUT_TEST_URL_HTML: ${{ inputs.test_url_html }}
        INPUT_COMMIT_SHA: ${{ inputs.commit_sha }}
        INPUT_RUN_ID: ${{ inputs.run_id }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_SERVER_URL: ${{ inputs.server_url }}
        INPUT_API_DOMAIN: ${{ inputs.api_domain }}
        INPUT_HMAC_SECRET: ${{ inputs.hmac_secret }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: ${{ github.action_path }}/update-badge-win.ps1
